###############################################################################
# Created by write_sdc
# Tue Oct 31 02:09:36 2023
###############################################################################
current_design des_Trojan
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 25.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {decrypt}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[10]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[11]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[12]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[13]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[14]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[15]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[16]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[17]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[18]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[19]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[20]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[21]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[22]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[23]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[24]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[25]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[26]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[27]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[28]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[29]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[30]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[31]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[32]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[33]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[34]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[35]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[36]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[37]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[38]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[39]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[40]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[41]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[42]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[43]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[44]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[45]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[46]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[47]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[48]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[49]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[50]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[51]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[52]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[53]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[54]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[55]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[56]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[57]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[58]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[59]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[5]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[60]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[61]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[62]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[63]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[6]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[7]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[8]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desIn[9]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {init}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[10]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[11]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[12]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[13]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[14]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[15]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[16]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[17]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[18]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[19]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[20]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[21]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[22]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[23]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[24]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[25]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[26]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[27]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[28]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[29]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[30]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[31]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[32]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[33]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[34]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[35]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[36]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[37]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[38]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[39]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[40]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[41]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[42]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[43]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[44]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[45]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[46]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[47]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[48]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[49]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[50]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[51]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[52]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[53]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[54]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[55]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[5]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[6]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[7]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[8]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {key[9]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reset}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[0]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[10]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[11]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[12]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[13]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[14]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[15]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[16]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[17]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[18]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[19]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[1]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[20]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[21]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[22]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[23]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[24]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[25]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[26]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[27]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[28]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[29]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[2]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[30]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[31]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[32]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[33]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[34]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[35]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[36]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[37]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[38]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[39]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[3]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[40]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[41]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[42]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[43]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[44]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[45]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[46]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[47]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[48]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[49]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[4]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[50]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[51]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[52]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[53]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[54]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[55]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[56]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[57]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[58]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[59]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[5]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[60]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[61]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[62]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[63]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[6]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[7]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[8]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {desOut_ff[9]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {finish}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {finish}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[63]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[62]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[61]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[60]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[59]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[58]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[57]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[56]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[55]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[54]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[53]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[52]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[51]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[50]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[49]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[48]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[47]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[46]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[45]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[44]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[43]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[42]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[41]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[40]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[39]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[38]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[37]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[36]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[35]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[34]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[33]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[32]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[31]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[30]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[29]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[28]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[27]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[26]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[25]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[24]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[23]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[22]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[21]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[20]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[19]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[18]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[17]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[16]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[15]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[14]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[13]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[12]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[11]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[10]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[9]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[8]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[7]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[6]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[5]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[4]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[3]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[2]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[1]}]
set_load -pin_load 0.0334 [get_ports {desOut_ff[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {decrypt}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {init}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reset}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[63]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[62]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[61]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[60]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[59]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[58]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[57]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[56]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[55]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[54]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[53]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[52]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[51]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[50]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[49]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[48]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[47]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[46]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[45]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[44]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[43]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[42]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[41]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[40]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[39]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[38]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[37]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[36]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[35]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[34]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[33]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[32]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {desIn[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[55]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[54]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[53]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[52]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[51]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[50]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[49]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[48]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[47]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[46]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[45]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[44]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[43]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[42]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[41]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[40]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[39]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[38]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[37]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[36]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[35]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[34]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[33]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[32]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {key[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_fanout 10.0000 [current_design]
